In [2]:
import numpy as np
from helpers import load_csv_data

In [3]:
yb, input_data, ids = load_csv_data("data/train.csv")

In [4]:
data = input_data
print(data)

[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]


In [5]:
mean_value = np.mean(data[data != -999.])

In [6]:
data[data == -999.] = mean_value

print(data)

[[138.47        51.655       97.827      ...   1.24        -2.475
  113.497     ]
 [160.937       68.768      103.235      ...  44.74998666  44.74998666
   46.226     ]
 [ 44.74998666 162.172      125.953      ...  44.74998666  44.74998666
   44.251     ]
 ...
 [105.457       60.526       75.839      ...  44.74998666  44.74998666
   41.992     ]
 [ 94.951       19.362       68.812      ...  44.74998666  44.74998666
    0.        ]
 [ 44.74998666  72.756       70.831      ...  44.74998666  44.74998666
    0.        ]]
